# Generated by Django 4.2.1 on 2023-06-05 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='заголовок')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('content', models.TextField(max_length=250, verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='превью')),
                ('create_data', models.DateField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('sign', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('views', models.IntegerField(default=0, verbose_name='количество просмотров')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=25, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=25, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=25, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Название'),
        ),
    ]
