# Generated by Django 4.2.1 on 2023-05-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_price_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(default='2020-01-01 00:00', verbose_name='Дата создания'),
        ),
    ]
