# Generated by Django 4.2.1 on 2023-06-04 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=25, verbose_name='slug')),
                ('content', models.CharField(max_length=250, verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='превью')),
                ('create_data', models.DateField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('sign', models.CharField(max_length=25, verbose_name='признак публикации')),
                ('views', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ('-create_data',),
            },
        ),
    ]
