# Generated by Django 4.2.1 on 2023-06-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_blogs_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ('-pk',), 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
