# Generated by Django 4.2.1 on 2023-06-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_blogs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
